### ISSUE TITLE
yld: Symbol not found: _kABPersonAddressCityKey

### ISSUE THREAD

**Issue by deokarDattatray** [paysafegroup/paysafe_sdk_ios#1]
If app is built with Xcode 8 and launched on iOS version lower than iOS 10 then it crashes with below error.
`yld: Symbol not found: _kABPersonAddressCityKey Referenced from: /Users/ajitemsahasrabuddhe/Library/Developer/CoreSimulator/Devices/83287726-DAB4-4319-9950-B4750F56DFAD/data/Containers/Bundle/Application/EB937A70-7404-49AA-966F-DF19720D824A/ChangeTransit.app/Frameworks/Paysafe.framework/Paysafe Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/PassKit.framework/PassKit in /Users/ajitemsahasrabuddhe/Library/Developer/CoreSimulator/Devices/83287726-DAB4-4319-9950-B4750F56DFAD/data/Containers/Bundle/Application/EB937A70-7404-49AA-966F-DF19720D824A/ChangeTransit.app/Frameworks/Paysafe.framework/Paysafe`

As suggested in some links i have added AddressBook Framework in app but still it is crashing.

Refer discussion here
https://github.com/OceanLabs/iOS-Print-SDK/issues/257

**Comment by nngenov** [comment]
Hey @deokarDattatray 
You can try our new version of the SDK :) 
It has some new features and new example apps
