### ISSUE TITLE
Example projects do not build

### ISSUE THREAD

**Issue by jcantin-nventive** [paysafegroup/paysafe_sdk_ios#2]
I took the latest version in the master branch of the repo and built the IOS_SDK project. I then tried to build the test project TestMerchAppExample_Obj-C and got the following errors:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

There were also errors with the tests:

/Users/user/Documents/paysafe_sdk_ios-master/paysafe_sdk_ios-master/Examples/TestMerchAppExample_Obj-C/TestMerchAppExample_Obj-CTests/TestMerchAppExample_Obj_CTests.m:11:1: Expected identifier or '('

/Users/user/Documents/paysafe_sdk_ios-master/paysafe_sdk_ios-master/Examples/TestMerchAppExample_Obj-C/TestMerchAppExample_Obj-CTests/TestMerchAppExample_Obj_CTests.m:48:1: '@end' must appear in an Objective-C context

/Users/user/Documents/paysafe_sdk_ios-master/paysafe_sdk_ios-master/Examples/TestMerchAppExample_Obj-C/TestMerchAppExample_Obj-CTests/TestMerchAppExample_Obj_CTests.m:24:1: Missing context for method declaration

/Users/user/Documents/paysafe_sdk_ios-master/paysafe_sdk_ios-master/Examples/TestMerchAppExample_Obj-C/TestMerchAppExample_Obj-CTests/TestMerchAppExample_Obj_CTests.m:30:1: Missing context for method declaration

/Users/user/Documents/paysafe_sdk_ios-master/paysafe_sdk_ios-master/Examples/TestMerchAppExample_Obj-C/TestMerchAppExample_Obj-CTests/TestMerchAppExample_Obj_CTests.m:36:1: Missing context for method declaration

/Users/user/Documents/paysafe_sdk_ios-master/paysafe_sdk_ios-master/Examples/TestMerchAppExample_Obj-C/TestMerchAppExample_Obj-CTests/TestMerchAppExample_Obj_CTests.m:43:1: Missing context for method declaration

I got these results by opening IOS_SDK.xcworkspace with Xcode 10.1

**Comment by nngenov** [comment]
Hey @jcantin-nventive, 
You could try our new examples with version 2.0.0 of the SDK
